### ISSUE TITLE
Only Pangya *.pak ?

### ISSUE THREAD

**Issue by imKota** [retreev/PangLib.PSP#1]
Hello, @pixeldesu!
Only Pangya *.pak supported?

I am trying to unpack file, but it's not working for me.
Can you test [file](https://www.mediafire.com/file/wdo2n8hklq3aamy/test.zip/file)?

**Comment by pixeldesu** [comment]
I looked at the file and I can't really discern any structure, or one that'd be common to the Pangya PAK file format, especially since Pangya's PAKs require two files (`psppackfilelist.pak` and `pspdata.pak`)

**Comment by imKota** [comment]
Too bad.
There is no meaningful information about the structure of this archive, and it is impossible for me to do debugging psp yet. The only thing I have come to is this:

![image](https://user-images.githubusercontent.com/24241471/133042057-6c992326-4b4f-4460-adee-f1b549a8ae70.png)


Maybe you have some ideas?

**Comment by pixeldesu** [comment]
Just from a screenshot and some code code branch info I don't think I'll be able to help you much.

What game are you reverse engineering here? Maybe someone already figured out the archive format for it!

**Comment by imKota** [comment]
> What game are you reverse engineering here?

[This game (japanese voiced psp version)](https://vndb.org/v3130), but I couldn't find any information.

> Just from a screenshot and some code code branch info I don't think I'll be able to help you much.

I have attached the archive below, maybe it will help. If you have the time and desire, I would be glad to have your help.
[EBOOT.zip](https://github.com/pangyatools/PangLib.PSP/files/7152494/EBOOT.zip)
